name: Publish

on:
  release:
    types:
      - published

jobs:
  build_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/install-dependencies

      - run: npx nx run-many -t build

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Publish packages
        if: github.ref == 'refs/heads/main'
        run: npx nx release publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }} # needed for publish to npm
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
