name: Release

on:
  push:
    branches:
      - main

jobs:
  lint_build_test_release:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write # needed for provenance data generation

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/install-dependencies

      - run: npx nx run-many -t lint test build

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Set up GitHub username and email
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clear the nx cache so the build happens again
        run: npx nx reset
        shell: bash

      - name: Create a github release
        if: github.ref == 'refs/heads/main'
        run: npx nx release --skip-publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }} # needed for publish to npm
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build storybook
        if: github.ref == 'refs/heads/main'
        run: npx nx run snow:build-storybook
        shell: bash

      - name: Run Chromatic
        if: github.ref == 'refs/heads/main'
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_SNOW_TOKEN }}
          storybookBuildDir: 'packages/snow/storybook-static'
          autoAcceptChanges: true
          exitZeroOnChanges: true
          exitOnceUploaded: true
