name: Release

on:
  push:
    branches:
      - main
permissions:
  actions: read
  contents: write
  id-token: write # needed for provenance data generation

jobs:
  lint_build_test_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/install-dependencies

      - run: npx nx run-many -t lint test build

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Create a patch release and publish
        if: github.ref == 'refs/heads/main'
        run: npx nx release patch --yes
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
